import 'package:flutter_riverpod/flutter_riverpod.dart';

class VideoIndex {
  //此数据模拟的联系人
  static Provider<List<Map<String, dynamic>>> contactProvider = Provider<List<Map<String, dynamic>>>((ref) {
    return [
      {"icon": "https://picsum.photos/seed/home/100/100", "title": "文件传输"},
      {"icon": "https://picsum.photos/seed/search/100/100", "title": "搜索"},
    ];
  });

  static List<Map<String, dynamic>> contentsindex = [
    {"icon": "https://picsum.photos/seed/home/100/100", "title": "首页", "region": "北京"},
    {"icon": "https://picsum.photos/seed/search/100/100", "title": "搜索", "region": "上海"},
    {"icon": "https://picsum.photos/seed/favorite/100/100", "title": "收藏", "region": "广州"},
    {"icon": "https://picsum.photos/seed/person/100/100", "title": "我的", "region": "深圳"},
    {"icon": "https://picsum.photos/seed/settings/100/100", "title": "设置", "region": "杭州"},
    {"icon": "https://picsum.photos/seed/mail/100/100", "title": "通知", "region": "成都"},
    {"icon": "https://picsum.photos/seed/chat/100/100", "title": "消息", "region": "武汉"},
    {"icon": "https://picsum.photos/seed/star/100/100", "title": "精选", "region": "西安"},
    {"icon": "https://picsum.photos/seed/cart/100/100", "title": "购物车", "region": "南京"},
    {"icon": "https://picsum.photos/seed/phone/100/100", "title": "电话", "region": "重庆"},
    {"icon": "https://picsum.photos/seed/email/100/100", "title": "邮箱", "region": "天津"},
    {"icon": "https://picsum.photos/seed/location/100/100", "title": "位置", "region": "苏州"},
    {"icon": "https://picsum.photos/seed/event/100/100", "title": "日程", "region": "郑州"},
    {"icon": "https://picsum.photos/seed/chat2/100/100", "title": "聊天", "region": "长沙"},
    {"icon": "https://picsum.photos/seed/rate/100/100", "title": "评分", "region": "青岛"},
    {"icon": "https://picsum.photos/seed/list/100/100", "title": "播放列表", "region": "大连"},
    {"icon": "https://picsum.photos/seed/wifi/100/100", "title": "无线网络", "region": "厦门"},
    {"icon": "https://picsum.photos/seed/brightness/100/100", "title": "亮度", "region": "宁波"},
    {"icon": "https://picsum.photos/seed/cloud/100/100", "title": "云存储", "region": "无锡"},
    {"icon": "https://picsum.photos/seed/music/100/100", "title": "音乐", "region": "佛山"},
    {"icon": "https://picsum.photos/seed/video/100/100", "title": "视频", "region": "沈阳"},
    {"icon": "https://picsum.photos/seed/game/100/100", "title": "游戏", "region": "济南"},
    {"icon": "https://picsum.photos/seed/school/100/100", "title": "学习", "region": "福州"},
    {"icon": "https://picsum.photos/seed/work/100/100", "title": "工作", "region": "哈尔滨"},
    {"icon": "https://picsum.photos/seed/restaurant/100/100", "title": "餐厅", "region": "长春"},
    {"icon": "https://picsum.photos/seed/hotel/100/100", "title": "酒店", "region": "太原"},
    {"icon": "https://picsum.photos/seed/flight/100/100", "title": "航班", "region": "石家庄"},
    {"icon": "https://picsum.photos/seed/train/100/100", "title": "火车", "region": "南昌"},
    {"icon": "https://picsum.photos/seed/car/100/100", "title": "驾车", "region": "贵阳"},
    {"icon": "https://picsum.photos/seed/bike/100/100", "title": "骑行", "region": "昆明"},
    {"icon": "https://picsum.photos/seed/fitness/100/100", "title": "健身", "region": "兰州"},
    {"icon": "https://picsum.photos/seed/hospital/100/100", "title": "医院", "region": "银川"},
    {"icon": "https://picsum.photos/seed/alert/100/100", "title": "紧急", "region": "西宁"},
    {"icon": "https://picsum.photos/seed/fireplace/100/100", "title": "壁炉", "region": "乌鲁木齐"},
    {"icon": "https://picsum.photos/seed/beach/100/100", "title": "海滩", "region": "海口"},
    {"icon": "https://picsum.photos/seed/casino/100/100", "title": "赌场", "region": "澳门"},
    {"icon": "https://picsum.photos/seed/attractions/100/100", "title": "景点", "region": "香港"},
    {"icon": "https://picsum.photos/seed/theater/100/100", "title": "影院", "region": "台北"},
    {"icon": "https://picsum.photos/seed/bag/100/100", "title": "购物袋", "region": "合肥"},
    {"icon": "https://picsum.photos/seed/redeem/100/100", "title": "兑换", "region": "南宁"},
    {"icon": "https://picsum.photos/seed/receipt/100/100", "title": "收据", "region": "拉萨"},
    {"icon": "https://picsum.photos/seed/schedule/100/100", "title": "日程", "region": "呼和浩特"},
    {"icon": "https://picsum.photos/seed/feedback/100/100", "title": "反馈", "region": "银川"},
    {"icon": "https://picsum.photos/seed/help/100/100", "title": "帮助", "region": "西宁"},
    {"icon": "https://picsum.photos/seed/info/100/100", "title": "信息", "region": "拉萨"},
    {"icon": "https://picsum.photos/seed/warning/100/100", "title": "警告", "region": "乌鲁木齐"},
    {"icon": "https://picsum.photos/seed/delete/100/100", "title": "删除", "region": "海口"},
    {"icon": "https://picsum.photos/seed/edit/100/100", "title": "编辑", "region": "澳门"},
    {"icon": "https://picsum.photos/seed/share/100/100", "title": "分享", "region": "香港"},
  ];

  final List<Map<String, dynamic>> videocontext = [
    {'video': 'assets/image/video_demo'},
    {'video': 'assets/image/video_demo1'},
    {'video': 'assets/image/video_demo2'},
    {'video': 'assets/image/video_demo3'},
    {'video': 'assets/image/video_demo4'},
    {'video': 'assets/image/video_demo5'},
    {'video': 'assets/image/video_demo6'},
    {'video': 'assets/image/video_demo7'},
    {'video': 'assets/image/video_demo8'},
  ];
  static List<Map<String, String>> gameList = [
    {'name': '贪吃蛇', 'desc': '经典复古游戏，控制小蛇不断吃食物长大，避免撞墙或咬到自己。', 'image': 'https://cdn-icons-png.flaticon.com/512/876/876235.png'},
    {'name': '俄罗斯方块', 'desc': '下落的方块需拼接成完整横线消除，考验反应与空间规划能力。', 'image': 'https://cdn-icons-png.flaticon.com/512/1092/1092640.png'},
    {'name': '植物大战僵尸', 'desc': '在草坪上种植各类植物，抵御一波波僵尸入侵，策略塔防经典之作。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095460.png'},
    {'name': '扫雷', 'desc': '根据数字提示避开地雷，逻辑推理找出所有安全区域。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095475.png'},
    {'name': '数独', 'desc': '填满 9×9 宫格，使每行、每列和每个 3×3 区域都包含 1-9 不重复数字。', 'image': 'https://cdn-icons-png.flaticon.com/512/3135/3135825.png'},
    {'name': '消消乐', 'desc': '交换相邻图标，凑齐三个相同图案即可消除，轻松解压的三消玩法。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095533.png'},
    {'name': '跳一跳', 'desc': '轻触屏幕控制小人跳跃到下一个平台，节奏与距离感是关键。', 'image': 'https://cdn-icons-png.flaticon.com/512/3695/3695382.png'},
    {'name': '合成大西瓜', 'desc': '将相同水果两两合并，最终目标是合成出大西瓜，魔性又上头。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095553.png'},
    {'name': '羊了个羊', 'desc': '号称“第二关难倒千万人”的消除游戏，道具与顺序决定成败。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095500.png'},
    {'name': '2048', 'desc': '滑动合并相同数字方块，目标是合成出 2048，策略与运气并存。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095450.png'},
    {'name': '愤怒的小鸟', 'desc': '用弹弓发射小鸟，摧毁猪堡结构，物理弹道与关卡设计巧妙结合。', 'image': 'https://cdn-icons-png.flaticon.com/512/1996/1996433.png'},
    {'name': '水果忍者', 'desc': '手指滑动切开飞出的水果，避开炸弹，享受爽快切割快感。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095520.png'},
    {'name': '纪念碑谷', 'desc': '操控视错觉建筑，引导沉默公主穿越不可能的几何迷宫，艺术感极强。', 'image': 'https://cdn-icons-png.flaticon.com/512/3695/3695390.png'},
    {'name': '开心消消乐', 'desc': '国民级三消游戏，数百关卡+可爱动物角色，老少皆宜。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095533.png'},
    {'name': '球球大作战', 'desc': '操控小球吞噬比你小的玩家，同时躲避更大的对手，实时多人竞技。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095490.png'},
    {'name': '我的世界（迷你版）', 'desc': '沙盒建造与生存探索，自由创造属于你的像素世界（简化体验版）。', 'image': 'https://cdn-icons-png.flaticon.com/512/1092/1092650.png'},
    {'name': '像素地牢', 'desc': 'Roguelike 地牢探险，每次进入地图随机生成，死亡即重来，硬核耐玩。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095480.png'},
    {'name': '割绳子', 'desc': '剪断绳子让糖果落入小怪兽口中，利用物理机关完成关卡挑战。', 'image': 'https://cdn-icons-png.flaticon.com/512/3095/3095510.png'},
    {'name': '涂鸦跳跃', 'desc': '控制小怪物不断向上跳跃，避开障碍、收集星星，永无止境的冒险。', 'image': 'https://cdn-icons-png.flaticon.com/512/3695/3695385.png'},
    {'name': 'Flappy Bird', 'desc': '点击屏幕让小鸟飞起，穿越密集的绿色管道，操作简单却极难通关。', 'image': 'https://cdn-icons-png.flaticon.com/512/1996/1996420.png'},
  ];
}
